name: gendiff-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build project
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: make install
      - run: npm link

      - name: Test & publish code coverage
        - run: make test
        - run: make test-coverage
        - run: make lint
          uses: paambaati/codeclimate-action@v3.0.0
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
          with:
            coverageCommand: make test-coverage
            debug: true
